# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from unikraft_cloud_platform.models.get_images200_response import GetImages200Response
from unikraft_cloud_platform.models.get_images_request_inner import GetImagesRequestInner

from unikraft_cloud_platform.api_client import ApiClient, RequestSerialized
from unikraft_cloud_platform.api_response import ApiResponse
from unikraft_cloud_platform.rest import RESTResponseType


class ImagesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def get_images(
        self,
        namespace: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=2048)]],
            Field(
                description="Filter images by namespace.  Note: Set the namespace to your Unikraft Cloud account name to list only your personal images. It can be `official` for listing only the official ones. In addition, the namespace can include the app name. For example, `${UKC_USER}/myapp` to list all your `myapp` images. "
            ),
        ] = None,
        tagged: Annotated[Optional[StrictBool], Field(description="Whether to include only tagged images. ")] = None,
        get_images_request_inner: Optional[List[Optional[GetImagesRequestInner]]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetImages200Response:
        """Get list of available images

        Retrieves all images visible to an account in OCI format.

        :param namespace: Filter images by namespace.  Note: Set the namespace to your Unikraft Cloud account name to list only your personal images. It can be `official` for listing only the official ones. In addition, the namespace can include the app name. For example, `${UKC_USER}/myapp` to list all your `myapp` images.
        :type namespace: str
        :param tagged: Whether to include only tagged images.
        :type tagged: bool
        :param get_images_request_inner:
        :type get_images_request_inner: List[GetImagesRequestInner]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_images_serialize(
            namespace=namespace,
            tagged=tagged,
            get_images_request_inner=get_images_request_inner,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "GetImages200Response",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def get_images_with_http_info(
        self,
        namespace: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=2048)]],
            Field(
                description="Filter images by namespace.  Note: Set the namespace to your Unikraft Cloud account name to list only your personal images. It can be `official` for listing only the official ones. In addition, the namespace can include the app name. For example, `${UKC_USER}/myapp` to list all your `myapp` images. "
            ),
        ] = None,
        tagged: Annotated[Optional[StrictBool], Field(description="Whether to include only tagged images. ")] = None,
        get_images_request_inner: Optional[List[Optional[GetImagesRequestInner]]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetImages200Response]:
        """Get list of available images

        Retrieves all images visible to an account in OCI format.

        :param namespace: Filter images by namespace.  Note: Set the namespace to your Unikraft Cloud account name to list only your personal images. It can be `official` for listing only the official ones. In addition, the namespace can include the app name. For example, `${UKC_USER}/myapp` to list all your `myapp` images.
        :type namespace: str
        :param tagged: Whether to include only tagged images.
        :type tagged: bool
        :param get_images_request_inner:
        :type get_images_request_inner: List[GetImagesRequestInner]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_images_serialize(
            namespace=namespace,
            tagged=tagged,
            get_images_request_inner=get_images_request_inner,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "GetImages200Response",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def get_images_without_preload_content(
        self,
        namespace: Annotated[
            Optional[Annotated[str, Field(strict=True, max_length=2048)]],
            Field(
                description="Filter images by namespace.  Note: Set the namespace to your Unikraft Cloud account name to list only your personal images. It can be `official` for listing only the official ones. In addition, the namespace can include the app name. For example, `${UKC_USER}/myapp` to list all your `myapp` images. "
            ),
        ] = None,
        tagged: Annotated[Optional[StrictBool], Field(description="Whether to include only tagged images. ")] = None,
        get_images_request_inner: Optional[List[Optional[GetImagesRequestInner]]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get list of available images

        Retrieves all images visible to an account in OCI format.

        :param namespace: Filter images by namespace.  Note: Set the namespace to your Unikraft Cloud account name to list only your personal images. It can be `official` for listing only the official ones. In addition, the namespace can include the app name. For example, `${UKC_USER}/myapp` to list all your `myapp` images.
        :type namespace: str
        :param tagged: Whether to include only tagged images.
        :type tagged: bool
        :param get_images_request_inner:
        :type get_images_request_inner: List[GetImagesRequestInner]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_images_serialize(
            namespace=namespace,
            tagged=tagged,
            get_images_request_inner=get_images_request_inner,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "GetImages200Response",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _get_images_serialize(
        self,
        namespace,
        tagged,
        get_images_request_inner,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {
            "GetImagesRequestInner": "",
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if namespace is not None:
            _query_params.append(("namespace", namespace))

        if tagged is not None:
            _query_params.append(("tagged", tagged))

        # process the header parameters
        # process the form parameters
        # process the body parameter
        if get_images_request_inner is not None:
            _body_params = get_images_request_inner

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(["application/json"])

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params["Content-Type"] = _content_type
        else:
            _default_content_type = self.api_client.select_header_content_type(["application/json"])
            if _default_content_type is not None:
                _header_params["Content-Type"] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = ["bearerAuth"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/images/list",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
