# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class AuthApi(ApiClient):
    """Low-level "plumbing" client for the `Auth` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    def check_authorization(
        self,
        *,
        body: models.CheckAuthorizationRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> AsyncIterator[models.CheckAuthorizationResponse]:
        """Check Authorization of Sign-In Request"""
        return self._stream(
            models.CheckAuthorizationResponse,
            method="POST",
            path="/v1/auth/check",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_authorization(
        self,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetAuthorizationResponse:
        """Get Authorization Status"""
        return await self._request(
            models.GetAuthorizationResponse,
            method="GET",
            path="/v1/auth",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def request_signin(
        self,
        *,
        body: models.RequestSigninRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.RequestSigninResponse:
        """Request Sign-In"""
        return await self._request(
            models.RequestSigninResponse,
            method="POST",
            path="/v1/auth/signin",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
