# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class ImagesApi(ApiClient):
    """Low-level "plumbing" client for the `Images` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def list_images(
        self,
        *,
        details: bool | None = None,
        namespace: list[str] | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.ListImagesResponse:
        """List Images"""
        return await self._request(
            models.ListImagesResponse,
            method="GET",
            path="/v1/images",
            query={
                "details": details,
                "namespace": namespace,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
