# Code generated by openapi-gen; DO NOT EDIT.
#
# Type definitions for the Unikraft Cloud API, generated from the OpenAPI
# specification. These mirror the wire format exactly.

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

# Enumerations, as Literal aliases rather than enum classes: the values stay
# plain strings, so `state == "running"` needs no import, and a value the server
# adds is one line to widen.


CloudProvider = Literal["manual", "aws"]
"""
CloudProvider identifies the cloud infrastructure provider where nodes are
provisioned.
"""

MutableNodeOperation = Literal["set", "add", "del"]
"""The operations available on a node's mutable properties."""

MutableNodeProperty = Literal["tags", "delete_lock", "ssh_keys"]
"""The mutable properties of a node which can be updated."""

NodeState = Literal[
    "unspecified",
    "pending",
    "provisioning",
    "configuring",
    "ready",
    "deprovisioning",
    "deprovisioned",
    "error",
    "maintenance",
]
"""
NodeState defines the provisioning lifecycle state of a machine which will
run the Unikraft Cloud Platform.
"""

ResponseStatus = Literal["success", "error", "partial_success"]
"""The response status of an API request."""


class AWSConfig(BaseModel):
    """AWSConfig contains AWS-specific configuration for node provisioning."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    vpc_id: str | None = None
    """
    The VPC ID where the instance will be launched. If not specified, the
    default VPC for the region will be used.
    """
    subnet_id: str | None = None
    """
    The subnet ID where the instance will be launched. If not specified,
    a subnet will be selected from the VPC.
    """
    security_group_ids: list[str] | None = None
    """
    Security group IDs to attach to the instance. If not specified, the
    default security group for the VPC will be used.
    """
    iam_instance_profile: str | None = None
    """The IAM instance profile ARN or name to attach to the instance."""
    root_volume: AWSEBSConfig | None = None
    """
    Root EBS volume configuration. If not specified, provider defaults
    will be used.
    """
    additional_volumes: list[AWSEBSConfig] | None = None
    """Additional EBS volumes to attach to the instance."""
    dedicated_host: bool
    """
    Whether to use a dedicated host. Dedicated hosts provide visibility and
    control over how instances are placed on physical servers.
    """
    placement_group: str | None = None
    """
    Placement group name for the instance. Placement groups influence how
    instances are placed on underlying hardware.
    """
    region: str
    """The AWS region where the machine is located."""
    machine_type: str
    """
    The AWS machine type. This determines the compute resources
    (CPU, memory, etc.) available on the machine. The valid values depend
    on the chosen provider.
    """


class AWSEBSConfig(BaseModel):
    """AWSEBSConfig defines the configuration for an AWS EBS volume."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    device_name: str | None = None
    """
    The device name (e.g., "/dev/sda1", "/dev/xvdf"). Required for
    additional volumes.
    """
    size_gib: int
    """Size of the volume in GiB."""
    volume_type: str
    """The volume type (gp3, gp2, io1, io2, st1, sc1, standard)."""
    iops: int | None = None
    """The number of IOPS. Only valid for io1, io2, and gp3 volumes."""
    throughput_mibps: int | None = None
    """The throughput in MiB/s. Only valid for gp3 volumes."""
    encrypted: bool
    """Whether the volume should be encrypted."""
    kms_key_id: str | None = None
    """
    The KMS key ID for encryption. If encrypted is true and this is not
    specified, the default EBS encryption key will be used.
    """
    delete_on_termination: bool
    """Whether to delete the volume when the instance is terminated."""


class CheckAuthorizationRequest(BaseModel):
    """The request message for checking authorization given a request ID."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    request_id: str
    """
    The request ID is a unique identifier for the request.  This is used to
    track the request in the system and should be provided by the client.
    """


class CheckAuthorizationResponse(BaseModel):
    """The response message for checking authorization."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: CheckAuthorizationResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """
    The operation time in microseconds.  This is the time it took to process
    the request and generate the response.
    """


class CheckAuthorizationResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    token: str
    """The authorization token which can be used to authenticate requests."""
    organization_name: str
    """The organization name the token is associated with."""
    organization_display_name: str
    """The display name of the organization the token is associated with."""
    registry: str
    """The global image registry."""


class CloudProviderConfig(BaseModel):
    """
    CloudProviderConfig contains provider-specific configuration for node
    provisioning.
    """

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    aws: AWSConfig | None = None
    """AWS-specific configuration."""


class DestroyNodeResponse(BaseModel):
    """Response message for deleting nodes."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: DestroyNodeResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """The operation time in microseconds."""


class DestroyNodeResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    nodes: list[Node] | None = None
    """The deleted nodes (with their final state before deletion)."""


class GetAuthorizationResponse(BaseModel):
    """The response message for getting authorization details."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: GetAuthorizationResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """
    The operation time in microseconds.  This is the time it took to process
    the request and generate the response.
    """


class GetAuthorizationResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    organization_name: str
    """The organization name the token is associated with."""
    organization_display_name: str
    """The display name of the organization the token is associated with."""
    registry: str
    """The global image registry."""


class Image(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str
    """The canonical name of the image."""
    tags: list[ImageTag] | None = None
    """The list of tags for the image.  Only populated when details are requested."""


class ImageTag(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str
    """The tag name."""
    digest: str
    """The digest for the tag."""
    size: int
    """The size of the image in bytes."""
    push_time: str
    """The push time of the image."""


class ListImagesResponse(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: ListImagesResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """
    The operation time in microseconds.  This is the time it took to process
    the request and generate the response.
    """


class ListImagesResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    images: list[Image] | None = None
    """The list of images."""


class ListMachineTypesResponse(BaseModel):
    """Response message for listing machine types."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: ListMachineTypesResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """The operation time in microseconds."""


class ListMachineTypesResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    machine_types: list[MachineType] | None = None
    """The list of available machine types."""


class ListMetroResponse(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: ListMetroResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """
    The operation time in microseconds.  This is the time it took to process
    the request and generate the response.
    """


class ListMetroResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    metros: list[Metro] | None = None
    """The list of metros."""


class ListNodesResponse(BaseModel):
    """Response message for getting nodes."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: ListNodesResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """The operation time in microseconds."""


class ListNodesResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    nodes: list[Node] | None = None
    """The list of nodes matching the request."""
    total_count: int
    """Total count of nodes matching the filters (for pagination)."""


class ListRegionsResponse(BaseModel):
    """Response message for listing regions."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: ListRegionsResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """The operation time in microseconds."""


class ListRegionsResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    regions: list[Region] | None = None
    """The list of available regions."""


class MachineType(BaseModel):
    """Information about an available machine type."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str
    """The machine type identifier (e.g., "m5.xlarge", "n2-standard-4")."""
    description: str | None = None
    """Human-readable description."""
    vcpus: int
    """Number of vCPUs."""
    memory_mib: int
    """Memory in MiB."""
    category: str | None = None
    """
    Machine category (e.g., "general-purpose", "compute-optimized",
    "memory-optimized").
    """
    available_regions: list[str] | None = None
    """Regions where this machine type is available."""
    nested_virtualization: bool
    """Whether this machine type supports nested virtualization."""


class Metro(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    uuid: str
    """The UUID of the metro."""
    endpoint: str
    """The API endpoint for the metro."""
    name: str
    """The name of the metro."""
    iata_code: str
    """The IATA code of the metro."""
    country: str
    """The country where the metro is located."""


class NameOrUUID(BaseModel):
    """An identifier for a resource.  Either a name or a UUID."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    uuid: str | None = None
    """The UUID of the resource."""
    name: str | None = None
    """The name of the resource."""


class Node(BaseModel):
    """
    Node represents a physical or virtual compute node provisioned on a
    cloud provider for use as part of the Unikraft Cloud infrastructure.

    Node nodes are the underlying compute resources where Unikraft Cloud
    instances run.  They are provisioned on-demand across multiple cloud
    providers and managed through a unified API.
    """

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    uuid: str
    """
    The UUID of the machine.

    This is a unique identifier for the machine that is generated when the
    machine is created. The UUID is used to reference the machine in API calls
    and
    can be used to identify the machine in all API calls that require a machine
    identifier.
    """
    name: str
    """
    The name of the machine.

    This is a human-readable name that can be used to identify the machine.
    The name must be unique within the context of your account. The name can
    also be used to identify the machine in API calls.
    """
    created_at: str
    """The time the machine was created."""
    updated_at: str | None = None
    """The time the machine was last updated."""
    state: NodeState
    """The current state of the machine."""
    state_message: str | None = None
    """
    An optional message providing additional information about the current
    state, particularly useful for error states.
    """
    cloudprovider: CloudProvider | None = None
    """The cloud provider where this machine is provisioned."""
    vcpus: int
    """The number of vCPUs available on this machine."""
    memory_mib: int
    """The amount of memory in MiB available on this machine."""
    ssh_keys: list[SSHKey] | None = None
    """The SSH keys configured for access to this machine."""
    public_ipv4: str | None = None
    """The public IPv4 address of the machine, if assigned."""
    public_ipv6: str | None = None
    """The public IPv6 address of the machine, if assigned."""
    private_ipv4: str | None = None
    """The private IPv4 address of the machine within the provider's network."""
    metro: str | None = None
    """The Unikraft Cloud metro this machine is associated with."""
    provider_instance_id: str | None = None
    """The provider-specific instance ID or resource identifier."""
    provider_config: CloudProviderConfig | None = None
    """Provider-specific configuration that was used to provision this node."""
    tags: dict[str, str] | None = None
    """User-defined tags for organizing and filtering nodes."""
    ready_at: str | None = None
    """The time when the machine became ready (entered READY state)."""
    uptime_seconds: int
    """The total uptime of the machine in seconds since it became ready."""
    delete_lock: bool
    """
    Whether the machine is protected from deletion. When true, delete operations
    will fail until this is set to false.
    """
    api_endpoint: str | None = None
    """The API endpoint for the node, used to connect to the node's platform SDK."""


class NodeActivateRequest(BaseModel):
    """The request message for certificate activation."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    csr: str
    """
    The certificate signing request (CSR) for the license which is base64
    encoded.
    """
    secret: str | None = None
    """
    An opaque secret for first-time activation. On renewal (where the node's
    public key is already known), this field is omitted and the CSR
    self-signature is used as proof of key possession.
    """
    serial: str | None = None
    """The serial number of the last issued certificate."""


class NodeActivateResponse(BaseModel):
    """The response message for certificate activation."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """/ An optional message providing additional information about the response."""
    data: NodeActivateResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """The operation time in microseconds."""


class NodeActivateResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    license: str
    """The issued license certificate in base64 URL encoded PEM format."""


class ProvisionNodeRequest(BaseModel):
    """Request message for creating a new node."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str | None = None
    """
    Optional name for the node. If not provided, a name will be
    auto-generated.
    """
    cloudprovider: CloudProvider | None = None
    """The cloud provider where the machine should be provisioned."""
    ssh_keys: list[SSHKey]
    """SSH keys for accessing the node. At least one key is required."""
    tags: dict[str, str] | None = None
    """Optional user-defined tags."""
    cloudprovider_config: CloudProviderConfig | None = None
    """Optional provider-specific configuration for advanced customization."""
    metro: str | None = None
    """The Unikraft Cloud metro to associate this machine with."""
    platform_config: dict[str, str] | None = None
    """
    Optional user overrides for platform configuration. Keys should be
    kebab-case (e.g., "vm-user-min-memory").
    """
    image_pulls: list[str] | None = None
    """Optional image references to pre-pull on the provisioned machine."""
    net_count: int | None = None
    """Optional network count override. If not specified, defaults to 1000."""


class ProvisionNodeResponse(BaseModel):
    """Response message for creating a node."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: ProvisionNodeResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """The operation time in microseconds."""


class ProvisionNodeResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    node: Node
    """The created node."""


class Region(BaseModel):
    """Information about an available region."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str
    """The region identifier (e.g., "us-east-1", "us-central1")."""
    iata: str
    """The IATA code for the region."""


class RequestSigninRequest(BaseModel):
    """The request message for a sign-in request."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    hostname: str
    """
    The hostname is the name of the machine making the request.  This is
    mandatory as it consitutes a unique identifier for the machine.
    """
    os: str | None = None
    """The operating system of the machine making the request."""
    os_version: str | None = None
    """
    The version of the operating system of the machine making the request, if
    available.

    For Android, it's like "10", "11", "12", etc.  For iOS and macOS it's like
    "15.6.1" or "12.4.0".  For Windows it's like "10.0.19044.1889". For FreeBSD
    it's like "12.3-STABLE".  For Linux, this is simply the kernel version on
    Linux, like "5.10.0-17-amd64".
    """
    container: bool | None = None
    """A best-effort whether the client is running in a container."""
    distro: str | None = None
    """The OS distribution, if known.  E.g. "debian", "ubuntu", "nixos", ..."""
    distro_version: str | None = None
    """The OS distribution version if known.  E.g. "20.04", ..."""
    distro_codename: str | None = None
    """TThe OS distribution codename if known.  E.g. "jammy", "bullseye", ..."""
    cli_version: str | None = None
    """
    The CLI version is the version of the Unikraft CLI that is making the
    request.
    """
    goarch: str | None = None
    """If available, the GOARCH value (of the built binary)."""
    goos: str | None = None
    """If available, the GOOS value (of the built binary)"""
    go_version: str | None = None
    """if available, the Go version binary was built with."""


class RequestSigninResponse(BaseModel):
    """The response message for a sign-in request."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: RequestSigninResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """
    The operation time in microseconds.  This is the time it took to process
    the request and generate the response.
    """


class RequestSigninResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    authorization_url: str
    """The full URL which can be used to remotely confirm the signin."""
    request_id: str
    """
    A unique identifier for the request.  This can be used to track the
    request in the system.
    """


class ResponseError(BaseModel):
    """The error response message for an API request."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: int
    """The HTTP status code of the error."""


class SSHKey(BaseModel):
    """SSHKey represents an SSH public key for authentication."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str
    """A name or label for this SSH key."""
    public_key: str
    """
    The SSH public key in OpenSSH format (e.g., "ssh-rsa AAAA... user@host"
    or "ssh-ed25519 AAAA... user@host").
    """


class UpdateNodePayload(BaseModel):
    """UpdateNodePayload contains the changes to apply to a node."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    property: MutableNodeProperty
    """The property to update."""
    operation: MutableNodeOperation
    """The operation to perform on the property."""
    value: str | None = None
    """
    The value for the update operation. The type depends on the property:
    - TAGS: google.protobuf.Struct with key-value pairs
    - DELETE_LOCK: google.protobuf.Value with boolean
    - SSH_KEYS: google.protobuf.ListValue with SSHKey objects
    """


class UpdateNodesResponse(BaseModel):
    """Response message for updating nodes."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: UpdateNodesResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """The operation time in microseconds."""


class UpdateNodesResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    nodes: list[Node] | None = None
    """The updated nodes."""


class WaitNodesResponse(BaseModel):
    """Response message for wait operations."""

    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    status: ResponseStatus
    """The status of the response."""
    message: str | None = None
    """An optional message providing additional information about the response."""
    data: WaitNodesResponseData | None = None
    """The response data for this request."""
    errors: list[ResponseError] | None = None
    """A list of errors which may have occurred during the request."""
    op_time_us: int
    """The operation time in microseconds."""


class WaitNodesResponseData(BaseModel):
    # Fields the specification does not describe are kept rather than dropped,
    # so a newly added one survives a round trip and does not break this client.
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    nodes: list[Node] | None = None
    """The nodes after reaching the desired state."""


# Annotations are deferred, so a model may name one defined further down. This
# resolves them all now: a reference that cannot be resolved becomes an error on
# import rather than a surprise at the first request.
for _model in (
    AWSConfig,
    AWSEBSConfig,
    CheckAuthorizationRequest,
    CheckAuthorizationResponse,
    CheckAuthorizationResponseData,
    CloudProviderConfig,
    DestroyNodeResponse,
    DestroyNodeResponseData,
    GetAuthorizationResponse,
    GetAuthorizationResponseData,
    Image,
    ImageTag,
    ListImagesResponse,
    ListImagesResponseData,
    ListMachineTypesResponse,
    ListMachineTypesResponseData,
    ListMetroResponse,
    ListMetroResponseData,
    ListNodesResponse,
    ListNodesResponseData,
    ListRegionsResponse,
    ListRegionsResponseData,
    MachineType,
    Metro,
    NameOrUUID,
    Node,
    NodeActivateRequest,
    NodeActivateResponse,
    NodeActivateResponseData,
    ProvisionNodeRequest,
    ProvisionNodeResponse,
    ProvisionNodeResponseData,
    Region,
    RequestSigninRequest,
    RequestSigninResponse,
    RequestSigninResponseData,
    ResponseError,
    SSHKey,
    UpdateNodePayload,
    UpdateNodesResponse,
    UpdateNodesResponseData,
    WaitNodesResponse,
    WaitNodesResponseData,
):
    _model.model_rebuild()
