# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class NodeActivationServiceApi(ApiClient):
    """Low-level "plumbing" client for the `NodeActivationService` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def node_activate(
        self,
        *,
        body: models.NodeActivateRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.NodeActivateResponse:
        """
        Activates a new node, or renews an existing node's license. For first-time
        activation, a secret must be provided. For renewal, the CSR self-signature
        is used as proof of key possession and the secret is omitted.

        A renewal request may optionally also carry an HTTP message signature
        (RFC 9421) made with the node's current stable private key. When present
        and valid, it authorizes the CSR's public key to become the node's new
        stable identity even if it differs from the current one -- i.e. key
        rotation: prove who you are with the old key, then switch to the new one
        named in the CSR.
        """
        return await self.request(
            models.NodeActivateResponse,
            method="POST",
            path="/v1/nodes/activate",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def node_deactivate(
        self,
        *,
        body: models.NodeDeactivateRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.NodeDeactivateResponse:
        """
        Deactivates a node's license so it can no longer renew. The node's
        issued certificate remains valid until it naturally expires -- this
        only prevents renewal. The request must carry an HTTP message signature
        (RFC 9421) made with the node's stable private key; the node is
        identified by the signature, the same mechanism used by the private
        node-facing APIs (e.g. NodeHeartbeat).
        """
        return await self.request(
            models.NodeDeactivateResponse,
            method="POST",
            path="/v1/nodes/deactivate",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
