# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class NodeServiceApi(ApiClient):
    """Low-level "plumbing" client for the `NodeService` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def destroy_node(
        self,
        *,
        force: bool | None = None,
        body: list[models.NameOrUUID],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DestroyNodeResponse:
        """Delete Node Nodes"""
        return await self._request(
            models.DestroyNodeResponse,
            method="DELETE",
            path="/v1/nodes",
            query={
                "force": force,
            },
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def destroy_node_by_uuid(
        self,
        uuid: str,
        *,
        force: bool | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DestroyNodeResponse:
        """Delete Node Node by UUID"""
        return await self._request(
            models.DestroyNodeResponse,
            method="DELETE",
            path=f"/v1/nodes/{uuid}",
            query={
                "force": force,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_node_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.ListNodesResponse:
        """Get Node Node by UUID"""
        return await self._request(
            models.ListNodesResponse,
            method="GET",
            path=f"/v1/nodes/{uuid}",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def list_machine_types(
        self,
        cloudprovider: models.CloudProvider,
        *,
        region: str | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.ListMachineTypesResponse:
        """List Machine Types"""
        return await self._request(
            models.ListMachineTypesResponse,
            method="GET",
            path=f"/v1/nodes/providers/{cloudprovider}/types",
            query={
                "region": region,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def list_nodes(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        cloudprovider: models.CloudProvider | None = None,
        state: models.NodeState | None = None,
        metro: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.ListNodesResponse:
        """List Node Nodes"""
        return await self._request(
            models.ListNodesResponse,
            method="GET",
            path="/v1/nodes",
            query={
                "uuid": uuid,
                "name": name,
                "cloudprovider": cloudprovider,
                "state": state,
                "metro": metro,
                "limit": limit,
                "offset": offset,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def list_regions(
        self,
        cloudprovider: models.CloudProvider,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.ListRegionsResponse:
        """List Regions"""
        return await self._request(
            models.ListRegionsResponse,
            method="GET",
            path=f"/v1/nodes/providers/{cloudprovider}/regions",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def provision_node(
        self,
        *,
        body: models.ProvisionNodeRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.ProvisionNodeResponse:
        """Create Node Node"""
        return await self._request(
            models.ProvisionNodeResponse,
            method="POST",
            path="/v1/nodes",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_node_by_uuid(
        self,
        uuid: str,
        *,
        body: list[models.UpdateNodePayload],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateNodesResponse:
        """Update Node Node by UUID"""
        return await self._request(
            models.UpdateNodesResponse,
            method="PATCH",
            path=f"/v1/nodes/{uuid}",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_nodes(
        self,
        *,
        property: list[models.MutableNodeProperty] | None = None,
        operation: list[models.MutableNodeOperation] | None = None,
        value: list[str] | None = None,
        body: list[models.NameOrUUID],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateNodesResponse:
        """Update Node Nodes"""
        return await self._request(
            models.UpdateNodesResponse,
            method="PATCH",
            path="/v1/nodes",
            query={
                "property": property,
                "operation": operation,
                "value": value,
            },
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def wait_node_by_uuid(
        self,
        uuid: str,
        *,
        states: list[models.NodeState] | None = None,
        timeout_ms: int | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.WaitNodesResponse:
        """Wait for Node Node State by UUID"""
        return await self._request(
            models.WaitNodesResponse,
            method="GET",
            path=f"/v1/nodes/{uuid}/wait",
            query={
                "states": states,
                "timeout_ms": timeout_ms,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def wait_nodes(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        states: list[models.NodeState] | None = None,
        timeout_ms: int | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.WaitNodesResponse:
        """Wait for Node Nodes States"""
        return await self._request(
            models.WaitNodesResponse,
            method="GET",
            path="/v1/nodes/wait",
            query={
                "uuid": uuid,
                "name": name,
                "states": states,
                "timeout_ms": timeout_ms,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
