# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class NodeActivationServiceApi(ApiClient):
    """Low-level "plumbing" client for the `NodeActivationService` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def node_activate(
        self,
        *,
        body: models.NodeActivateRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.NodeActivateResponse:
        """
        Activates a new node, or renews an existing node's license. For first-time
        activation, a secret must be provided. For renewal, the CSR self-signature
        is used as proof of key possession and the secret is omitted.
        """
        return await self._request(
            models.NodeActivateResponse,
            method="POST",
            path="/v1/nodes/activate",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
