# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from unikraft_cloud_platform.models.autoscale_policy_step import AutoscalePolicyStep
from typing import Optional, Set
from typing_extensions import Self


class AutoscalePolicy(BaseModel):
    """
    Description of [autoscale policies](https://unikraft.cloud/docs/api/v1/autoscale/#autoscale-policies). See [policy creation endpoint](https://unikraft.cloud/docs/api/v1/autoscale/#policy_create).
    """  # noqa: E501

    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None, description="The name of the policy. "
    )
    metric: Optional[StrictStr] = Field(default="cpu", description="Metric to monitor. ")
    type: Optional[StrictStr] = Field(default=None, description="Type of autoscale policy. ")
    adjustment_type: Optional[StrictStr] = Field(default="change", description="Type of adjustment. ")
    steps: Optional[Annotated[List[AutoscalePolicyStep], Field(max_length=253)]] = None
    __properties: ClassVar[List[str]] = ["name", "metric", "type", "adjustment_type", "steps"]

    @field_validator("metric")
    def metric_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["cpu"]):
            raise ValueError("must be one of enum values ('cpu')")
        return value

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["step"]):
            raise ValueError("must be one of enum values ('step')")
        return value

    @field_validator("adjustment_type")
    def adjustment_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["change", "exact", "percent"]):
            raise ValueError("must be one of enum values ('change', 'exact', 'percent')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AutoscalePolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in steps (list)
        _items = []
        if self.steps:
            for _item_steps in self.steps:
                if _item_steps:
                    _items.append(_item_steps.to_dict())
            _dict["steps"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AutoscalePolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "metric": obj.get("metric") if obj.get("metric") is not None else "cpu",
                "type": obj.get("type"),
                "adjustment_type": obj.get("adjustment_type") if obj.get("adjustment_type") is not None else "change",
                "steps": [AutoscalePolicyStep.from_dict(_item) for _item in obj["steps"]]
                if obj.get("steps") is not None
                else None,
            }
        )
        return _obj
