# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from unikraft_cloud_platform.models.autoscale_config_master import AutoscaleConfigMaster
from unikraft_cloud_platform.models.autoscale_policy import AutoscalePolicy
from typing import Optional, Set
from typing_extensions import Self


class AutoscaleConfig(BaseModel):
    """
    AutoscaleConfig
    """  # noqa: E501

    status: Optional[Annotated[str, Field(strict=True, max_length=12)]] = Field(
        default=None,
        description="`success` on success, `unconfigured` if autoscale is not configured, or `error` if the request failed. ",
    )
    uuid: Optional[UUID] = Field(default=None, description="The UUID of the service. ")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None, description="The name of the service. "
    )
    enabled: Optional[StrictBool] = Field(default=None, description="Whether autoscale is enabled. ")
    min_size: Optional[Annotated[int, Field(le=1, strict=True, ge=1)]] = Field(
        default=None, description="Minimum number of instances. "
    )
    max_size: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(
        default=None, description="Maximum number of instances. Maximum number is determined by the quota. "
    )
    warmup_time_ms: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(
        default=None,
        description="Length of [warmup phase](https://unikraft.cloud/docs/api/v1/autoscale/#warmup-and-cooldown) in milliseconds. ",
    )
    cooldown_time_ms: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(
        default=None,
        description="Length of [cooldown phase](https://unikraft.cloud/docs/api/v1/autoscale/#warmup-and-cooldown) in milliseconds. ",
    )
    master: Optional[AutoscaleConfigMaster] = None
    policies: Optional[Annotated[List[AutoscalePolicy], Field(max_length=253)]] = None
    __properties: ClassVar[List[str]] = [
        "status",
        "uuid",
        "name",
        "enabled",
        "min_size",
        "max_size",
        "warmup_time_ms",
        "cooldown_time_ms",
        "master",
        "policies",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["success", "unconfigured", "failure"]):
            raise ValueError("must be one of enum values ('success', 'unconfigured', 'failure')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AutoscaleConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of master
        if self.master:
            _dict["master"] = self.master.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in policies (list)
        _items = []
        if self.policies:
            for _item_policies in self.policies:
                if _item_policies:
                    _items.append(_item_policies.to_dict())
            _dict["policies"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AutoscaleConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "uuid": obj.get("uuid"),
                "name": obj.get("name"),
                "enabled": obj.get("enabled"),
                "min_size": obj.get("min_size"),
                "max_size": obj.get("max_size"),
                "warmup_time_ms": obj.get("warmup_time_ms"),
                "cooldown_time_ms": obj.get("cooldown_time_ms"),
                "master": AutoscaleConfigMaster.from_dict(obj["master"]) if obj.get("master") is not None else None,
                "policies": [AutoscalePolicy.from_dict(_item) for _item in obj["policies"]]
                if obj.get("policies") is not None
                else None,
            }
        )
        return _obj
