# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from unikraft_cloud_platform.models.certificate_service_groups_inner import CertificateServiceGroupsInner
from unikraft_cloud_platform.models.certificate_validation import CertificateValidation
from typing import Optional, Set
from typing_extensions import Self


class Certificate(BaseModel):
    """
    SSL Certificate.
    """  # noqa: E501

    status: Optional[StrictStr] = Field(
        default=None, description="The status of the response.  Note: Not when listing all existing certificates. "
    )
    uuid: Optional[UUID] = Field(default=None, description="The UUID of the certificate. ")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None, description="The name of the certificate. "
    )
    created_at: Optional[datetime] = Field(default=None, description="Date and time of creation in ISO8601. ")
    common_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None, description="Common name (CN) of the certificate. "
    )
    state: Optional[StrictStr] = Field(
        default=None,
        description="Current state of the certificate.  A certificate can be in one of the following states:  State     | Description ----------|------------ `pending` | The certificate request is pending while the certificate is being requested from the certification authority. During this phase any service using this certificate is not available if this is not a renewal. `valid`   | The certificate is valid and can be used for services. `error`   | The certificate request failed after multiple attempts. This can happen, for example, if your DNS configuration is not correct, you run into Let’s Encrypt™ quota limits, or the domain validation process failed for some other reason. There won’t be any further automatic attempts. If you need assistence please contact us via [support@unikraft.cloud](mailto:support@unikraft.cloud). ",
    )
    validation: Optional[CertificateValidation] = None
    subject: Optional[Annotated[str, Field(strict=True, max_length=8388608)]] = Field(
        default=None, description="Certificate subject. "
    )
    issuer: Optional[Annotated[str, Field(strict=True, max_length=8388608)]] = Field(
        default=None, description="Certificate issuer. "
    )
    serial_number: Optional[Annotated[str, Field(strict=True, max_length=8388608)]] = Field(
        default=None, description="Certificate serial number. "
    )
    not_before: Optional[datetime] = Field(
        default=None, description="Date and time of beginning of validity in ISO8601. "
    )
    not_after: Optional[datetime] = Field(default=None, description="Expiration date and time in ISO8601. ")
    service_groups: Optional[Annotated[List[CertificateServiceGroupsInner], Field(max_length=253)]] = Field(
        default=None, description="Services using this certificate. "
    )
    __properties: ClassVar[List[str]] = [
        "status",
        "uuid",
        "name",
        "created_at",
        "common_name",
        "state",
        "validation",
        "subject",
        "issuer",
        "serial_number",
        "not_before",
        "not_after",
        "service_groups",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["success", "failure"]):
            raise ValueError("must be one of enum values ('success', 'failure')")
        return value

    @field_validator("state")
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["valid", "pending", "error"]):
            raise ValueError("must be one of enum values ('valid', 'pending', 'error')")
        return value

    @field_validator("subject")
    def subject_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z]+?=(?:(?![a-zA-Z]+?=.*?).)*$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z]+?=(?:(?![a-zA-Z]+?=.*?).)*$/")
        return value

    @field_validator("issuer")
    def issuer_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([a-zA-Z]+?=(?:(?![a-zA-Z]+?=.*?).)*,*)*$", value):
            raise ValueError(r"must validate the regular expression /^([a-zA-Z]+?=(?:(?![a-zA-Z]+?=.*?).)*,*)*$/")
        return value

    @field_validator("serial_number")
    def serial_number_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[0-9a-fA-F]{1,64}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-fA-F]{1,64}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Certificate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of validation
        if self.validation:
            _dict["validation"] = self.validation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in service_groups (list)
        _items = []
        if self.service_groups:
            for _item_service_groups in self.service_groups:
                if _item_service_groups:
                    _items.append(_item_service_groups.to_dict())
            _dict["service_groups"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Certificate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "uuid": obj.get("uuid"),
                "name": obj.get("name"),
                "created_at": obj.get("created_at"),
                "common_name": obj.get("common_name"),
                "state": obj.get("state"),
                "validation": CertificateValidation.from_dict(obj["validation"])
                if obj.get("validation") is not None
                else None,
                "subject": obj.get("subject"),
                "issuer": obj.get("issuer"),
                "serial_number": obj.get("serial_number"),
                "not_before": obj.get("not_before"),
                "not_after": obj.get("not_after"),
                "service_groups": [CertificateServiceGroupsInner.from_dict(_item) for _item in obj["service_groups"]]
                if obj.get("service_groups") is not None
                else None,
            }
        )
        return _obj
