# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class CreateCertificateRequest(BaseModel):
    """
    CreateCertificateRequest
    """  # noqa: E501

    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="The name of the certificate to upload.  Note: If no name is specified a random name of the form `<cn>-X` is auto-generated, where `<cn>` is the common name and `X` is a 5 character long random alphanumeric suffix. For wildcard domains the wildcard part is cut off. ",
    )
    cn: Annotated[str, Field(strict=True, max_length=255)] = Field(description="The common name of the certificate. ")
    chain: Annotated[str, Field(strict=True, max_length=8388608)] = Field(
        description="The chain of the certificate in PEM format. "
    )
    pkey: Annotated[str, Field(strict=True, max_length=8388608)] = Field(
        description="The private key of the certificate in PEM format. "
    )
    __properties: ClassVar[List[str]] = ["name", "cn", "chain", "pkey"]

    @field_validator("chain")
    def chain_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-----BEGIN CERTIFICATE-----.+-----END CERTIFICATE-----", value):
            raise ValueError(
                r"must validate the regular expression /^-----BEGIN CERTIFICATE-----.+-----END CERTIFICATE-----/"
            )
        return value

    @field_validator("pkey")
    def pkey_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-----BEGIN PRIVATE KEY-----.+-----END PRIVATE KEY-----", value):
            raise ValueError(
                r"must validate the regular expression /^-----BEGIN PRIVATE KEY-----.+-----END PRIVATE KEY-----/"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCertificateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCertificateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {"name": obj.get("name"), "cn": obj.get("cn"), "chain": obj.get("chain"), "pkey": obj.get("pkey")}
        )
        return _obj
