# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from unikraft_cloud_platform.models.create_autoscale_config_request_master import CreateAutoscaleConfigRequestMaster
from typing import Optional, Set
from typing_extensions import Self


class CreateAutoscaleConfigRequest(BaseModel):
    """
    CreateAutoscaleConfigRequest
    """  # noqa: E501

    uuid: Optional[UUID] = Field(
        default=None,
        description="The UUID of the service for which to create a configuration.  Note: This property is mutually exclusive with `name` and either `uuid` or `name` are required. ",
    )
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="The name of the service for which to create a configuration.  Note: This property is mutually exclusive with `name` and either `uuid` or `name` are required. ",
    )
    min_size: Optional[Annotated[int, Field(le=1, strict=True, ge=1)]] = Field(
        default=1, description="Minimum number of instances. "
    )
    max_size: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(
        default=4, description="Maximum number of instances. "
    )
    warmup_time_ms: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(
        default=1000,
        description="Length of [warmup phase](https://unikraft.cloud/docs/api/v1/autoscale/#warmup-and-cooldown) in milliseconds. ",
    )
    cooldown_time_ms: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(
        default=1000,
        description="Length of [cooldown phase](https://unikraft.cloud/docs/api/v1/autoscale/#warmup-and-cooldown) in milliseconds. ",
    )
    master: Optional[CreateAutoscaleConfigRequestMaster] = None
    __properties: ClassVar[List[str]] = [
        "uuid",
        "name",
        "min_size",
        "max_size",
        "warmup_time_ms",
        "cooldown_time_ms",
        "master",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAutoscaleConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of master
        if self.master:
            _dict["master"] = self.master.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAutoscaleConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "uuid": obj.get("uuid"),
                "name": obj.get("name"),
                "min_size": obj.get("min_size") if obj.get("min_size") is not None else 1,
                "max_size": obj.get("max_size") if obj.get("max_size") is not None else 4,
                "warmup_time_ms": obj.get("warmup_time_ms") if obj.get("warmup_time_ms") is not None else 1000,
                "cooldown_time_ms": obj.get("cooldown_time_ms") if obj.get("cooldown_time_ms") is not None else 1000,
                "master": CreateAutoscaleConfigRequestMaster.from_dict(obj["master"])
                if obj.get("master") is not None
                else None,
            }
        )
        return _obj
