# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class CreateInstanceRequestScaleToZero(BaseModel):
    """
    With conventional cloud platforms you need to keep at least one instance running at all times to be able to respond to incoming requests. Performing a just-in-time cold boot is simply too time-consuming and would create a response latency of multiple seconds. This is not the case with Unikraft Cloud. Instances on Unikraft Cloud are able to cold boot within milliseconds, which allows us to perform low-latency scale-to-zero.  To enable scale-to-zero for an instance it is sufficient to add a `scale_to_zero` configuration block. Unikraft Cloud will then put the instance into standby if there is no traffic to your service within the window of a cooldown period. When there is new traffic coming in, it is automatically started again.  If you have a heavyweight application that takes long to cold boot or has bad first request latency (e.g., with JIT compilation) consider to enable [stateful scale-to-zero](https://unikraft.cloud/docs/api/v1/instances/#scaletozero_stateful).
    """  # noqa: E501

    policy: StrictStr = Field(
        description="With the scale-to-zero policy you define under which circumstances Unikraft Cloud should put your instance into standby.  Unikraft Cloud currently supports the following scale-to-zero policies:  Policy | Description -------|------------ `on`   | Scale-to-zero is enabled. When there are no TCP connections or HTTP requests for the duration of the cooldown time, the instance is put into standby `off`  | Scale-to-zero is not enabled. The instance keep on running until manually stopped `idle` | Same as `on`, but also puts the instance into standby when there are TCP connections established that have been inactive for the duration of the cooldown time. The connections remain established and incoming packets wake up the instance. Scale-to-zero does not happen while there are active HTTP requests (i.e., traffic on ports, which have been marked with the `http` handler as described [here](https://unikraft.cloud/docs/api/v1/services#handlers)) "
    )
    stateful: Optional[StrictBool] = Field(
        default=False,
        description="Whether to use [stateful](https://unikraft.cloud/docs/api/v1/instances/#scaletozero_stateful) scale-to-zero. ",
    )
    cooldown_time_ms: Optional[Annotated[int, Field(le=86400000, strict=True, ge=0)]] = Field(
        default=1000, description="Cooldown time in milliseconds. "
    )
    __properties: ClassVar[List[str]] = ["policy", "stateful", "cooldown_time_ms"]

    @field_validator("policy")
    def policy_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["on", "off", "idle"]):
            raise ValueError("must be one of enum values ('on', 'off', 'idle')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateInstanceRequestScaleToZero from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateInstanceRequestScaleToZero from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "policy": obj.get("policy"),
                "stateful": obj.get("stateful") if obj.get("stateful") is not None else False,
                "cooldown_time_ms": obj.get("cooldown_time_ms") if obj.get("cooldown_time_ms") is not None else 1000,
            }
        )
        return _obj
