# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from unikraft_cloud_platform.models.create_instance_request_env import CreateInstanceRequestEnv
from unikraft_cloud_platform.models.create_instance_request_scale_to_zero import CreateInstanceRequestScaleToZero
from unikraft_cloud_platform.models.create_instance_request_service_group import CreateInstanceRequestServiceGroup
from unikraft_cloud_platform.models.create_instance_request_volumes_inner import CreateInstanceRequestVolumesInner
from typing import Optional, Set
from typing_extensions import Self


class CreateInstanceRequest(BaseModel):
    """
    CreateInstanceRequest
    """  # noqa: E501

    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="The name of the instance. The instance will receive a DNS entry in your private network of the form `<name>.internal`.  Note: If no name is specified a random name of the form `<app>-X` is auto-generated, where `<app>` is the application name taken from `image` (e.g., `myapp` for `../myapp:latest`) and `X` is a 5 character long random alphanumeric suffix. ",
    )
    image: Annotated[str, Field(strict=True, max_length=8388608)] = Field(
        description="Digest of the image that the instance uses.  Note: The image tag (e.g., `latest`) is translated by Unikraft Cloud to the image digest that was assigned the tag at the time of instance creation. The image is pinned to this particular version. "
    )
    args: Optional[Annotated[List[Annotated[str, Field(strict=True, max_length=8388608)]], Field(max_length=253)]] = (
        Field(default=None, description="Application arguments. ")
    )
    env: Optional[CreateInstanceRequestEnv] = None
    memory_mb: Optional[Annotated[int, Field(le=4096, strict=True, ge=16)]] = Field(
        default=None, description="Amount of memory assigned to the instance in megabytes. "
    )
    restart_policy: Optional[StrictStr] = Field(
        default="never",
        description="When an instance stops either because the application exits or the instance crashes, Unikraft Cloud can auto-restart your instance. Auto-restarts are performed according to the restart policy configured for a particular instance. The policy can have the following values:  Policy       | Description -------------|------------ `always`     | Always restart the instance when the stop is initiated from within the instance (i.e., the application exits or the instance crashes). `on-failure` | Only restart the instance if it crashes. `never`      | Never restart the instance (default). ",
    )
    scale_to_zero: Optional[CreateInstanceRequestScaleToZero] = None
    volumes: Optional[Annotated[List[Optional[CreateInstanceRequestVolumesInner]], Field(max_length=253)]] = Field(
        default=None, description="Description of [volumes](https://unikraft.cloud/docs/api/v1/volumes). "
    )
    service_group: Optional[CreateInstanceRequestServiceGroup] = None
    autostart: Optional[StrictBool] = Field(
        default=False, description="Autostart behavior. If `true` the instance will start immediately after creation. "
    )
    replicas: Optional[Annotated[int, Field(le=253, strict=True, ge=0)]] = Field(
        default=0, description="Number of instance replicas to create with these properties. "
    )
    wait_timeout_ms: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(
        default=0,
        description="Timeout to wait for all new instances to reach running state in milliseconds. No wait performed for `0`  Note: Only valid if `autostart` is `true`. The maximum timeout may vary. Use `-1` for the largest possible value. ",
    )
    features: Optional[Annotated[List[StrictStr], Field(max_length=253)]] = Field(
        default=None,
        description="Set of features to enable for the instance (see [below](https://unikraft.cloud/docs/api/v1/instances/#features)). ",
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "image",
        "args",
        "env",
        "memory_mb",
        "restart_policy",
        "scale_to_zero",
        "volumes",
        "service_group",
        "autostart",
        "replicas",
        "wait_timeout_ms",
        "features",
    ]

    @field_validator("image")
    def image_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(
            r"^(?:(?=[^:\/]{1,253})(?!-)[a-zA-Z0-9-]{1,63}(?<!-)(?:\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-))*(?::[0-9]{1,5})?\/)?((?![._-])(?:[a-z0-9._-]*)(?<![._-])(?:\/(?![._-])[a-z0-9._-]*(?<![._-]))*)(?::(?![.-])[a-zA-Z0-9_.-]{1,128})?$",
            value,
        ):
            raise ValueError(
                r"must validate the regular expression /^(?:(?=[^:\/]{1,253})(?!-)[a-zA-Z0-9-]{1,63}(?<!-)(?:\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-))*(?::[0-9]{1,5})?\/)?((?![._-])(?:[a-z0-9._-]*)(?<![._-])(?:\/(?![._-])[a-z0-9._-]*(?<![._-]))*)(?::(?![.-])[a-zA-Z0-9_.-]{1,128})?$/"
            )
        return value

    @field_validator("restart_policy")
    def restart_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["always", "on-failure", "never"]):
            raise ValueError("must be one of enum values ('always', 'on-failure', 'never')")
        return value

    @field_validator("features")
    def features_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(["scale-to-zero", "delete-on-stop"]):
                raise ValueError("each list item must be one of ('scale-to-zero', 'delete-on-stop')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateInstanceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of env
        if self.env:
            _dict["env"] = self.env.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scale_to_zero
        if self.scale_to_zero:
            _dict["scale_to_zero"] = self.scale_to_zero.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in volumes (list)
        _items = []
        if self.volumes:
            for _item_volumes in self.volumes:
                if _item_volumes:
                    _items.append(_item_volumes.to_dict())
            _dict["volumes"] = _items
        # override the default output from pydantic by calling `to_dict()` of service_group
        if self.service_group:
            _dict["service_group"] = self.service_group.to_dict()
        # set to None if service_group (nullable) is None
        # and model_fields_set contains the field
        if self.service_group is None and "service_group" in self.model_fields_set:
            _dict["service_group"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateInstanceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "image": obj.get("image"),
                "args": obj.get("args"),
                "env": CreateInstanceRequestEnv.from_dict(obj["env"]) if obj.get("env") is not None else None,
                "memory_mb": obj.get("memory_mb"),
                "restart_policy": obj.get("restart_policy") if obj.get("restart_policy") is not None else "never",
                "scale_to_zero": CreateInstanceRequestScaleToZero.from_dict(obj["scale_to_zero"])
                if obj.get("scale_to_zero") is not None
                else None,
                "volumes": [CreateInstanceRequestVolumesInner.from_dict(_item) for _item in obj["volumes"]]
                if obj.get("volumes") is not None
                else None,
                "service_group": CreateInstanceRequestServiceGroup.from_dict(obj["service_group"])
                if obj.get("service_group") is not None
                else None,
                "autostart": obj.get("autostart") if obj.get("autostart") is not None else False,
                "replicas": obj.get("replicas") if obj.get("replicas") is not None else 0,
                "wait_timeout_ms": obj.get("wait_timeout_ms") if obj.get("wait_timeout_ms") is not None else 0,
                "features": obj.get("features"),
            }
        )
        return _obj
