# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self


class CreateInstanceRequestVolumesInner(BaseModel):
    """
    CreateInstanceRequestVolumesInner
    """  # noqa: E501

    uuid: Optional[UUID] = Field(
        default=None,
        description="UUID of an existing volume. Must be in `available` [state](https://unikraft.cloud/docs/api/v1/volumes#states). ",
    )
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="The name of the volume to attach.  Note: You need to specify either `uuid`, `name`, or `size_mb`. Specifying `size_mb` will create a new [volume](https://unikraft.cloud/docs/api/v1/volumes) and attach it to the instance. The volume will receive an auto-generated name. ",
    )
    at: Optional[Annotated[str, Field(strict=True, max_length=8388608)]] = Field(
        default=None, description="Path of the mountpoint. Must be empty. Automatically created if it does not exist. "
    )
    readonly: Optional[StrictBool] = Field(
        default=False, description="Whether the volume should be mounted read-only. "
    )
    __properties: ClassVar[List[str]] = []

    @field_validator("at")
    def at_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(\/[ a-zA-Z0-9._-]*)*$", value):
            raise ValueError(r"must validate the regular expression /^(\/[ a-zA-Z0-9._-]*)*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateInstanceRequestVolumesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateInstanceRequestVolumesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({})
        return _obj
