# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self


class DeleteInstances200ResponseDataInstancesInner(BaseModel):
    """
    DeleteInstances200ResponseDataInstancesInner
    """  # noqa: E501

    status: Optional[StrictStr] = Field(
        default=None, description="The status of the response.  Note: Not when listing all existing instances. "
    )
    uuid: Optional[UUID] = Field(default=None, description="The UUID of the instance. ")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="The name of the instance. The instance will receive a DNS entry in your private network of the form `<name>.internal`.  Note: If no name is specified a random name of the form `<app>-X` is auto-generated, where `<app>` is the application name taken from `image` (e.g., `myapp` for `../myapp:latest`) and `X` is a 5 character long random alphanumeric suffix. ",
    )
    previous_state: Optional[StrictStr] = Field(
        default=None,
        description="An instance can be in one of the following states:  State     | Description ----------|------------ `stopped` | The instance is not running and does not count against live resource quotas. Connections cannot be established. `starting`| The instance is booting up. This usually takes just a few milliseconds. `running` | Your application's main entry point has been reached. `draining`| The instance is draining connections before shutting down. No new connections can be established. `stopping`| The instance is shutting down. `standby` | The instance has [scale-to-zero](https://unikraft.cloud/docs/api/v1/autoscale#scaletozero) enabled. The instance is not running, but will be automatically started when there are incoming requests. ",
    )
    __properties: ClassVar[List[str]] = ["status", "uuid", "name", "previous_state"]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["success", "error"]):
            raise ValueError("must be one of enum values ('success', 'error')")
        return value

    @field_validator("previous_state")
    def previous_state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["stopped", "starting", "running", "draining", "stopping", "standby"]):
            raise ValueError(
                "must be one of enum values ('stopped', 'starting', 'running', 'draining', 'stopping', 'standby')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeleteInstances200ResponseDataInstancesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeleteInstances200ResponseDataInstancesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "uuid": obj.get("uuid"),
                "name": obj.get("name"),
                "previous_state": obj.get("previous_state"),
            }
        )
        return _obj
