# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self


class GetInstanceLogsRequestInner(BaseModel):
    """
    GetInstanceLogsRequestInner
    """  # noqa: E501

    uuid: Optional[UUID] = Field(
        default=None,
        description="The UUID of the instance to retrieve logs for.  Note: This property is mutually exclusive with `name` and either `uuid` or `name` are required. ",
    )
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="The name of the instance to retrieve logs for.  Note: This property is mutually exclusive with `uuid` and either `uuid` or `name` are required. ",
    )
    offset: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483647)]] = Field(
        default=-4096,
        description="The byte offset of the log output to receive. A negative sign makes the offset relative to the end of the log. ",
    )
    limit: Optional[Annotated[int, Field(le=16383, strict=True, ge=0)]] = Field(
        default=4096, description="The amount of bytes to return at most. "
    )
    __properties: ClassVar[List[str]] = ["uuid", "name", "offset", "limit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetInstanceLogsRequestInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetInstanceLogsRequestInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "uuid": obj.get("uuid"),
                "name": obj.get("name"),
                "offset": obj.get("offset") if obj.get("offset") is not None else -4096,
                "limit": obj.get("limit") if obj.get("limit") is not None else 4096,
            }
        )
        return _obj
