# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class Image(BaseModel):
    """
    Image
    """  # noqa: E501

    digest: Optional[Annotated[str, Field(strict=True, max_length=8388608)]] = Field(
        default=None, description="Image digest to uniquely identify this image. "
    )
    tags: Optional[
        Annotated[List[Annotated[str, Field(strict=True, max_length=8388608)]], Field(min_length=0, max_length=253)]
    ] = Field(default=None, description="Tags referencing this image.")
    initrd: Optional[StrictBool] = Field(
        default=None, description="Indicates if the image comes with an init ramdisk. "
    )
    size_in_bytes: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None, description="Total size of the image on disk in bytes including the initrd, if any. "
    )
    args: Optional[Annotated[str, Field(strict=True, max_length=8388608)]] = Field(
        default=None,
        description="Default application arguments of the image. Dismissed if the instance specifies application arguments. ",
    )
    kernel_args: Optional[Annotated[str, Field(strict=True, max_length=8388608)]] = Field(
        default=None,
        description="Unikraft kernel arguments hardcoded into the image. Prepended to the kernel arguments set by Unikraft Cloud. ",
    )
    labels: Optional[Dict[str, Annotated[str, Field(strict=True, max_length=8388608)]]] = Field(
        default=None,
        description="Key value pairs of image labels (e.g., used as defaults for instance configuration). ",
    )
    __properties: ClassVar[List[str]] = ["digest", "tags", "initrd", "size_in_bytes", "args", "kernel_args", "labels"]

    @field_validator("digest")
    def digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z_0-9]+[a-zA-Z_0-9]+((:|@sha256:)[a-zA-Z_0-9]+)?$", value):
            raise ValueError(
                r"must validate the regular expression /^[a-zA-Z_0-9]+[a-zA-Z_0-9]+((:|@sha256:)[a-zA-Z_0-9]+)?$/"
            )
        return value

    @field_validator("args")
    def args_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([a-zA-Z0-9=_-]+ *)*$", value):
            raise ValueError(r"must validate the regular expression /^([a-zA-Z0-9=_-]+ *)*$/")
        return value

    @field_validator("kernel_args")
    def kernel_args_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([a-zA-Z0-9=_-]+ *)*$", value):
            raise ValueError(r"must validate the regular expression /^([a-zA-Z0-9=_-]+ *)*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Image from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Image from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "digest": obj.get("digest"),
                "tags": obj.get("tags"),
                "initrd": obj.get("initrd"),
                "size_in_bytes": obj.get("size_in_bytes"),
                "args": obj.get("args"),
                "kernel_args": obj.get("kernel_args"),
                "labels": obj.get("labels"),
            }
        )
        return _obj
