# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self


class InstanceNetworkInterfacesInner(BaseModel):
    """
    InstanceNetworkInterfacesInner
    """  # noqa: E501

    uuid: Optional[UUID] = Field(default=None, description="The UUID of the network interface. ")
    private_ip: Optional[Annotated[str, Field(strict=True, max_length=15)]] = Field(
        default=None, description="Private IPv4 of network interface. "
    )
    mac: Optional[Annotated[str, Field(strict=True, max_length=17)]] = Field(
        default=None, description="MAC address of the network interface. "
    )
    rx_bytes: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None,
        description="Amount of bytes received from interface.  Note: Only with `metrics=true` query parameter. ",
    )
    rx_packets: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None,
        description="Count of packets received from interface.  Note: Only with `metrics=true` query parameter. ",
    )
    tx_bytes: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None,
        description="Amount of bytes transmitted over interface.  Note: Only with `metrics=true` query parameter. ",
    )
    tx_packets: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None,
        description="Count of packets transmitted over interface.  Note: Only with `metrics=true` query parameter. ",
    )
    __properties: ClassVar[List[str]] = [
        "uuid",
        "private_ip",
        "mac",
        "rx_bytes",
        "rx_packets",
        "tx_bytes",
        "tx_packets",
    ]

    @field_validator("mac")
    def mac_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$", value):
            raise ValueError(r"must validate the regular expression /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceNetworkInterfacesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceNetworkInterfacesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "uuid": obj.get("uuid"),
                "private_ip": obj.get("private_ip"),
                "mac": obj.get("mac"),
                "rx_bytes": obj.get("rx_bytes"),
                "rx_packets": obj.get("rx_packets"),
                "tx_bytes": obj.get("tx_bytes"),
                "tx_packets": obj.get("tx_packets"),
            }
        )
        return _obj
