# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from unikraft_cloud_platform.models.instance_service_group_domains_inner_certificate import (
    InstanceServiceGroupDomainsInnerCertificate,
)
from typing import Optional, Set
from typing_extensions import Self


class InstanceServiceGroupDomainsInner(BaseModel):
    """
    InstanceServiceGroupDomainsInner
    """  # noqa: E501

    name: Annotated[str, Field(strict=True, max_length=255)] = Field(
        description="Publicly accessible domain name.  Note: The services published by the service will be accessible under the given domain names. If `name` is a fully-qualified domain name, that is it ends with a dot (`.`), the domain name is taken as-is. Otherwise, the metro’s domain name is appended (e.g., `my-project` expands to `my-project.fra0.kraft.host`). If the given domain name is already in use by the current or a different user the operation fails. In addition, certain domain names cannot be used (e.g., `www.fra0.kraft.host`). "
    )
    certificate: Optional[InstanceServiceGroupDomainsInnerCertificate] = None
    __properties: ClassVar[List[str]] = ["name", "certificate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceServiceGroupDomainsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of certificate
        if self.certificate:
            _dict["certificate"] = self.certificate.to_dict()
        # set to None if certificate (nullable) is None
        # and model_fields_set contains the field
        if self.certificate is None and "certificate" in self.model_fields_set:
            _dict["certificate"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceServiceGroupDomainsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "certificate": InstanceServiceGroupDomainsInnerCertificate.from_dict(obj["certificate"])
                if obj.get("certificate") is not None
                else None,
            }
        )
        return _obj
