# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self


class InstanceMetrics(BaseModel):
    """
    InstanceMetrics
    """  # noqa: E501

    status: Optional[StrictStr] = Field(default=None, description="The status of the response. ")
    uuid: Optional[UUID] = Field(default=None, description="The UUID of the instance. ")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None, description="The name of the instance. "
    )
    rss_bytes: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None,
        description="Resident set size of the VMM in bytes.  Note: The resident set size (RSS) specifies the amount of physical memory that has been touched by the instance and is currently reserved for the instance on the Unikraft Cloud server. The RSS grows until the instance has touched all memory assigned to it via the `memory_mb` setting and may also exceed this value as supporting services running outside the instance acquire memory. The RSS is different from the current amount of memory allocated by the application, which is likely to fluctuate over the lifetime of the application. The RSS is not a cumulative metric. When the instance is stopped `rss` goes down to 0. ",
    )
    cpu_time_ms: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None, description="Consumed CPU time in milliseconds. "
    )
    rx_bytes: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None, description="Total amount of bytes received from network. "
    )
    rx_packets: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None, description="Total count of packets received from network. "
    )
    tx_bytes: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None, description="Total amount of bytes transmitted over network. "
    )
    tx_packets: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None, description="Total count of packets transmitted over network. "
    )
    nconns: Optional[Annotated[int, Field(le=65535, strict=True, ge=0)]] = Field(
        default=None, description="Number of currently established inbound connections (non-HTTP). "
    )
    nreqs: Optional[Annotated[int, Field(le=65535, strict=True, ge=0)]] = Field(
        default=None, description="Number of in-flight HTTP requests. "
    )
    nqueued: Optional[Annotated[int, Field(le=65535, strict=True, ge=0)]] = Field(
        default=None, description="Number of queued inbound connections and HTTP requests. "
    )
    ntotal: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]] = Field(
        default=None, description="Total number of inbound connections and HTTP requests handled. "
    )
    __properties: ClassVar[List[str]] = [
        "status",
        "uuid",
        "name",
        "rss_bytes",
        "cpu_time_ms",
        "rx_bytes",
        "rx_packets",
        "tx_bytes",
        "tx_packets",
        "nconns",
        "nreqs",
        "nqueued",
        "ntotal",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["success", "error"]):
            raise ValueError("must be one of enum values ('success', 'error')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "uuid": obj.get("uuid"),
                "name": obj.get("name"),
                "rss_bytes": obj.get("rss_bytes"),
                "cpu_time_ms": obj.get("cpu_time_ms"),
                "rx_bytes": obj.get("rx_bytes"),
                "rx_packets": obj.get("rx_packets"),
                "tx_bytes": obj.get("tx_bytes"),
                "tx_packets": obj.get("tx_packets"),
                "nconns": obj.get("nconns"),
                "nreqs": obj.get("nreqs"),
                "nqueued": obj.get("nqueued"),
                "ntotal": obj.get("ntotal"),
            }
        )
        return _obj
