# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from unikraft_cloud_platform.models.instance_service_group_domains_inner import InstanceServiceGroupDomainsInner
from typing import Optional, Set
from typing_extensions import Self


class InstanceServiceGroup(BaseModel):
    """
    Description of the service that the instance is part of.  Note: Only if attached to a service.
    """  # noqa: E501

    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="The name of an existing service.  Note: You need to specify either an existing [service](https://unikraft.cloud/docs/api/v1/services) via `uuid` or `name`, or provide a description of a new service. If a description for a new service is provided, the service is created and the instance attached. The service will receive an auto-generated name. Specifying an empty `service_group` object creates a new service with no services published. ",
    )
    uuid: Optional[UUID] = Field(default=None, description="UUID of an existing service. ")
    domains: Optional[Annotated[List[InstanceServiceGroupDomainsInner], Field(max_length=253)]] = Field(
        default=None,
        description="Description of domains to associate with the service.  Default: auto-generated Note: If `name` is specified without also providing a domain, a domain is derived from `name` by appending an 8 characters long random alphanumeric suffix and the metro's domain name. For example, setting the name to `my-project` without also providing a domain results in an auto-generated domain of `my-project-<random>.fra0.kraft.host`. ",
    )
    __properties: ClassVar[List[str]] = ["name", "uuid", "domains"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceServiceGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in domains (list)
        _items = []
        if self.domains:
            for _item_domains in self.domains:
                if _item_domains:
                    _items.append(_item_domains.to_dict())
            _dict["domains"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceServiceGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "uuid": obj.get("uuid"),
                "domains": [InstanceServiceGroupDomainsInner.from_dict(_item) for _item in obj["domains"]]
                if obj.get("domains") is not None
                else None,
            }
        )
        return _obj
