# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from unikraft_cloud_platform.models.create_instance_request_service_group_domains_inner import (
    CreateInstanceRequestServiceGroupDomainsInner,
)
from unikraft_cloud_platform.models.get_services200_response_data_service_groups_inner_instances_inner import (
    GetServices200ResponseDataServiceGroupsInnerInstancesInner,
)
from unikraft_cloud_platform.models.service_mapping import ServiceMapping
from typing import Optional, Set
from typing_extensions import Self


class Service(BaseModel):
    """
    Service
    """  # noqa: E501

    status: Optional[StrictStr] = Field(default=None, description="The status of the response. ")
    uuid: Optional[UUID] = Field(default=None, description="The UUID of the service. ")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None, description="The name of the service. "
    )
    created_at: Optional[datetime] = Field(default=None, description="Date and time of creation in ISO8601. ")
    persistent: Optional[StrictBool] = Field(
        default=None, description="Indicates if the service will stay alive even after the last instance detached. "
    )
    autoscale: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if the service has [autoscale](https://unikraft.cloud/docs/api/v1/autoscale) enabled. ",
    )
    soft_limit: Optional[Annotated[int, Field(le=65535, strict=True, ge=1)]] = Field(
        default=None,
        description="Per-instance connection [soft limit](https://unikraft.cloud/docs/api/v1/services/#limits). ",
    )
    hard_limit: Optional[Annotated[int, Field(le=65535, strict=True, ge=1)]] = Field(
        default=None,
        description="Per-instance connection [hard limit](https://unikraft.cloud/docs/api/v1/services/#limits). ",
    )
    services: Optional[Annotated[List[ServiceMapping], Field(max_length=253)]] = Field(
        default=None, description="Description of published network services. "
    )
    domains: Optional[Annotated[List[CreateInstanceRequestServiceGroupDomainsInner], Field(max_length=253)]] = None
    instances: Optional[
        Annotated[List[GetServices200ResponseDataServiceGroupsInnerInstancesInner], Field(max_length=253)]
    ] = Field(default=None, description="Instances attached to this service")
    __properties: ClassVar[List[str]] = [
        "status",
        "uuid",
        "name",
        "created_at",
        "persistent",
        "autoscale",
        "soft_limit",
        "hard_limit",
        "services",
        "domains",
        "instances",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["success", "error"]):
            raise ValueError("must be one of enum values ('success', 'error')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Service from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in services (list)
        _items = []
        if self.services:
            for _item_services in self.services:
                if _item_services:
                    _items.append(_item_services.to_dict())
            _dict["services"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in domains (list)
        _items = []
        if self.domains:
            for _item_domains in self.domains:
                if _item_domains:
                    _items.append(_item_domains.to_dict())
            _dict["domains"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in instances (list)
        _items = []
        if self.instances:
            for _item_instances in self.instances:
                if _item_instances:
                    _items.append(_item_instances.to_dict())
            _dict["instances"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Service from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "uuid": obj.get("uuid"),
                "name": obj.get("name"),
                "created_at": obj.get("created_at"),
                "persistent": obj.get("persistent"),
                "autoscale": obj.get("autoscale"),
                "soft_limit": obj.get("soft_limit"),
                "hard_limit": obj.get("hard_limit"),
                "services": [ServiceMapping.from_dict(_item) for _item in obj["services"]]
                if obj.get("services") is not None
                else None,
                "domains": [CreateInstanceRequestServiceGroupDomainsInner.from_dict(_item) for _item in obj["domains"]]
                if obj.get("domains") is not None
                else None,
                "instances": [
                    GetServices200ResponseDataServiceGroupsInnerInstancesInner.from_dict(_item)
                    for _item in obj["instances"]
                ]
                if obj.get("instances") is not None
                else None,
            }
        )
        return _obj
