# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from unikraft_cloud_platform.models.user_quota_limits import UserQuotaLimits
from unikraft_cloud_platform.models.user_quota_used import UserQuotaUsed
from typing import Optional, Set
from typing_extensions import Self


class UserQuota(BaseModel):
    """
    UserQuota
    """  # noqa: E501

    used: Optional[UserQuotaUsed] = None
    hard: Optional[Dict[str, Any]] = Field(default=None, description="Hard quota limits. ")
    limits: Optional[UserQuotaLimits] = None
    __properties: ClassVar[List[str]] = ["used", "hard", "limits"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserQuota from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of used
        if self.used:
            _dict["used"] = self.used.to_dict()
        # override the default output from pydantic by calling `to_dict()` of limits
        if self.limits:
            _dict["limits"] = self.limits.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserQuota from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "used": UserQuotaUsed.from_dict(obj["used"]) if obj.get("used") is not None else None,
                "hard": obj.get("hard"),
                "limits": UserQuotaLimits.from_dict(obj["limits"]) if obj.get("limits") is not None else None,
            }
        )
        return _obj
