# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class UserQuotaLimits(BaseModel):
    """
    Additional limits.
    """  # noqa: E501

    min_memory_mb: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=16)]] = Field(
        default=None, description="Minimum amount of memory assigned to live instances in megabytes. "
    )
    max_memory_mb: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=4096)]] = Field(
        default=None, description="Maximum amount of memory assigned to live instances in megabytes. "
    )
    min_volume_mb: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(
        default=None, description="Minimum size of a volume in megabytes. "
    )
    max_volume_mb: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1024)]] = Field(
        default=None, description="Maximum size of a volume in megabytes. "
    )
    min_autoscale_size: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(
        default=None,
        description="Minimum size of an autoscale group  Note: These restrict the `min_size` and `max_size` fields of the [autoscale configuration](https://unikraft.cloud/docs/api/v1/autoscale/#basics). If both values are `1` autoscale is not enabled for your account. If you want to explore autoscale for your services, please contact us via [support@unikraft.cloud](mailto:support@unikraft.cloud). ",
    )
    max_autoscale_size: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(
        default=None,
        description="Maximum size of an autoscale group.  Note: These restrict the `min_size` and `max_size` fields of the [autoscale configuration](https://unikraft.cloud/docs/api/v1/autoscale/#basics). ",
    )
    __properties: ClassVar[List[str]] = [
        "min_memory_mb",
        "max_memory_mb",
        "min_volume_mb",
        "max_volume_mb",
        "min_autoscale_size",
        "max_autoscale_size",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserQuotaLimits from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserQuotaLimits from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "min_memory_mb": obj.get("min_memory_mb"),
                "max_memory_mb": obj.get("max_memory_mb"),
                "min_volume_mb": obj.get("min_volume_mb"),
                "max_volume_mb": obj.get("max_volume_mb"),
                "min_autoscale_size": obj.get("min_autoscale_size"),
                "max_autoscale_size": obj.get("max_autoscale_size"),
            }
        )
        return _obj
