# coding: utf-8

"""
Unikraft Cloud Platform

This is the API of the Unikraft Cloud Platform.

The version of the OpenAPI document: 0.6.0
Contact: info@unikraft.cloud
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self


class UserQuotaUsed(BaseModel):
    """
    Used quota.
    """  # noqa: E501

    instances: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(
        default=None, description="Number of created instances. "
    )
    live_instances: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(
        default=None, description="Number of instances that are not in the `stopped` state. "
    )
    live_memory_mb: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(
        default=None,
        description="Amount of memory assigned to instances that are not in the `stopped` state in megabytes. ",
    )
    service_groups: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(
        default=None, description="Number of services. "
    )
    services: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(
        default=None, description="Number of published network ports over all existing services. "
    )
    volumes: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = Field(
        default=None, description="Number of volumes. "
    )
    total_volume_mb: Optional[Annotated[int, Field(le=1048576, strict=True, ge=0)]] = Field(
        default=None, description="Total size of all volumes in megabytes. "
    )
    __properties: ClassVar[List[str]] = [
        "instances",
        "live_instances",
        "live_memory_mb",
        "service_groups",
        "services",
        "volumes",
        "total_volume_mb",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserQuotaUsed from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserQuotaUsed from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "instances": obj.get("instances"),
                "live_instances": obj.get("live_instances"),
                "live_memory_mb": obj.get("live_memory_mb"),
                "service_groups": obj.get("service_groups"),
                "services": obj.get("services"),
                "volumes": obj.get("volumes"),
                "total_volume_mb": obj.get("total_volume_mb"),
            }
        )
        return _obj
