# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping

from ...core.http import UNSET, ApiClient, TimeoutOption, comma_separated
from . import models_gen as models


class AuditApi(ApiClient):
    """Low-level "plumbing" client for the `audit` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    def subscribe_audit_events(
        self,
        *,
        events: list[models.AuditEventType] | None = None,
        uuid: list[str] | None = None,
        tags: list[str] | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> AsyncIterator[models.AuditEvent]:
        """Subscribe to Audit Events"""
        return self.stream(
            models.AuditEvent,
            method="GET",
            path="/v1/audit",
            query={
                "events": comma_separated(events),
                "uuid": comma_separated(uuid),
                "tags": comma_separated(tags),
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
