# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class ImagesApi(ApiClient):
    """Low-level "plumbing" client for the `Images` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def get_image_store(
        self,
        *,
        digest: str | None = None,
        tag: str | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetImagesResponse:
        """Get Images in Store"""
        return await self._request(
            models.GetImagesResponse,
            method="GET",
            path="/v1/image-store",
            query={
                "digest": digest,
                "tag": tag,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_images(
        self,
        *,
        digest: str | None = None,
        tag: str | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetImagesResponse:
        """Get Images"""
        return await self._request(
            models.GetImagesResponse,
            method="GET",
            path="/v1/images",
            query={
                "digest": digest,
                "tag": tag,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
