# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class ImagesApi(ApiClient):
    """Low-level "plumbing" client for the `images` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def get_image_store(
        self,
        *,
        digest: str | None = None,
        tag: str | None = None,
        body: list[models.GetImagesRequestTagOrDigest] | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetImagesResponse:
        """Get Images in Store"""
        return await self.request(
            models.GetImagesResponse,
            method="GET",
            path="/v1/image-store",
            query={
                "digest": digest,
                "tag": tag,
            },
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_images(
        self,
        *,
        digest: str | None = None,
        tag: str | None = None,
        body: list[models.GetImagesRequestTagOrDigest] | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetImagesResponse:
        """Get Images"""
        return await self.request(
            models.GetImagesResponse,
            method="GET",
            path="/v1/images",
            query={
                "digest": digest,
                "tag": tag,
            },
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def pin_images(
        self,
        *,
        body: list[models.PinImageRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.PinImagesResponse:
        """Pin Images"""
        return await self.request(
            models.PinImagesResponse,
            method="POST",
            path="/v1/images",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def unpin_images(
        self,
        *,
        body: list[models.UnpinImageRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UnpinImagesResponse:
        """Unpin Images"""
        return await self.request(
            models.UnpinImagesResponse,
            method="DELETE",
            path="/v1/images",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
