# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class InstancesApi(ApiClient):
    """Low-level "plumbing" client for the `Instances` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def create_checkpoint_instances(
        self,
        *,
        body: list[models.CreateCheckpointInstancesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.CreateCheckpointInstancesResponse:
        """Create checkpoint instances"""
        return await self._request(
            models.CreateCheckpointInstancesResponse,
            method="POST",
            path="/v1/instances/checkpoints",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def create_instance(
        self,
        *,
        body: models.CreateInstanceRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.CreateInstanceResponse:
        """Create Instance"""
        return await self._request(
            models.CreateInstanceResponse,
            method="POST",
            path="/v1/instances",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def create_template_instances(
        self,
        *,
        body: list[models.CreateTemplateInstancesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.CreateTemplateInstancesResponse:
        """Create template instances from Instances"""
        return await self._request(
            models.CreateTemplateInstancesResponse,
            method="POST",
            path="/v1/instances/templates",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_checkpoint_instance_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteCheckpointInstancesResponse:
        """Delete checkpoint instance by UUID"""
        return await self._request(
            models.DeleteCheckpointInstancesResponse,
            method="DELETE",
            path=f"/v1/instances/checkpoints/{uuid}",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_checkpoint_instances(
        self,
        *,
        body: list[models.NameOrUUID],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteCheckpointInstancesResponse:
        """Delete checkpoint instances"""
        return await self._request(
            models.DeleteCheckpointInstancesResponse,
            method="DELETE",
            path="/v1/instances/checkpoints",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_instance_by_uuid(
        self,
        uuid: str,
        *,
        body: models.DeleteInstanceByUUIDRequestBody | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteInstancesResponse:
        """Delete Instance by UUID"""
        return await self._request(
            models.DeleteInstancesResponse,
            method="DELETE",
            path=f"/v1/instances/{uuid}",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_instances(
        self,
        *,
        body: list[models.DeleteInstanceRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteInstancesResponse:
        """Delete Instances"""
        return await self._request(
            models.DeleteInstancesResponse,
            method="DELETE",
            path="/v1/instances",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_template_instance_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteTemplateInstancesResponse:
        """Delete template instance by UUID"""
        return await self._request(
            models.DeleteTemplateInstancesResponse,
            method="DELETE",
            path=f"/v1/instances/templates/{uuid}",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_template_instances(
        self,
        *,
        body: list[models.NameOrUUID],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteTemplateInstancesResponse:
        """Delete template instances"""
        return await self._request(
            models.DeleteTemplateInstancesResponse,
            method="DELETE",
            path="/v1/instances/templates",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_checkpoint_history(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetCheckpointHistoryResponse:
        """Get checkpoint history"""
        return await self._request(
            models.GetCheckpointHistoryResponse,
            method="GET",
            path="/v1/instances/checkpoints/history",
            query={
                "uuid": uuid,
                "name": name,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_checkpoint_history_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetCheckpointHistoryResponse:
        """Get checkpoint history by UUID"""
        return await self._request(
            models.GetCheckpointHistoryResponse,
            method="GET",
            path=f"/v1/instances/checkpoints/{uuid}/history",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_checkpoint_instance_by_uuid(
        self,
        uuid: str,
        *,
        details: bool | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetCheckpointInstancesResponse:
        """Get checkpoint instance by UUID"""
        return await self._request(
            models.GetCheckpointInstancesResponse,
            method="GET",
            path=f"/v1/instances/checkpoints/{uuid}",
            query={
                "details": details,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_checkpoint_instances(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        details: bool | None = None,
        count: int | None = None,
        tags: list[str] | None = None,
        from_: str | None = None,
        order: models.PaginationOrder | None = None,
        sortby: models.PaginationSortBy | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetCheckpointInstancesResponse:
        """List checkpoint instances"""
        return await self._request(
            models.GetCheckpointInstancesResponse,
            method="GET",
            path="/v1/instances/checkpoints",
            query={
                "uuid": uuid,
                "name": name,
                "details": details,
                "count": count,
                "tags": tags,
                "from": from_,
                "order": order,
                "sortby": sortby,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_instance_by_uuid(
        self,
        uuid: str,
        *,
        details: bool | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetInstancesResponse:
        """Get Instance by UUID"""
        return await self._request(
            models.GetInstancesResponse,
            method="GET",
            path=f"/v1/instances/{uuid}",
            query={
                "details": details,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_instance_history(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetCheckpointHistoryResponse:
        """Get instances checkpoint history"""
        return await self._request(
            models.GetCheckpointHistoryResponse,
            method="GET",
            path="/v1/instances/history",
            query={
                "uuid": uuid,
                "name": name,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_instance_history_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetCheckpointHistoryResponse:
        """Get instance checkpoint history by UUID"""
        return await self._request(
            models.GetCheckpointHistoryResponse,
            method="GET",
            path=f"/v1/instances/{uuid}/history",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_instance_logs(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        offset: list[int] | None = None,
        limit: list[int] | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetInstancesLogsResponse:
        """Get Instances Logs"""
        return await self._request(
            models.GetInstancesLogsResponse,
            method="GET",
            path="/v1/instances/log",
            query={
                "uuid": uuid,
                "name": name,
                "offset": offset,
                "limit": limit,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_instance_logs_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetInstancesLogsResponse:
        """Get Instance Logs by UUID"""
        return await self._request(
            models.GetInstancesLogsResponse,
            method="GET",
            path=f"/v1/instances/{uuid}/log",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_instance_metrics(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetInstancesMetricsResponse:
        """Get Instances Metrics"""
        return await self._request(
            models.GetInstancesMetricsResponse,
            method="GET",
            path="/v1/instances/metrics",
            query={
                "uuid": uuid,
                "name": name,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_instance_metrics_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetInstancesMetricsResponse:
        """Get Instance Metrics by UUID"""
        return await self._request(
            models.GetInstancesMetricsResponse,
            method="GET",
            path=f"/v1/instances/{uuid}/metrics",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_instances(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        details: bool | None = None,
        count: int | None = None,
        from_: str | None = None,
        tags: list[str] | None = None,
        order: models.PaginationOrder | None = None,
        sortby: models.PaginationSortBy | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetInstancesResponse:
        """List Instances"""
        return await self._request(
            models.GetInstancesResponse,
            method="GET",
            path="/v1/instances",
            query={
                "uuid": uuid,
                "name": name,
                "details": details,
                "count": count,
                "from": from_,
                "tags": tags,
                "order": order,
                "sortby": sortby,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_template_instance_by_uuid(
        self,
        uuid: str,
        *,
        details: bool | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetTemplateInstancesResponse:
        """Get template instance by UUID"""
        return await self._request(
            models.GetTemplateInstancesResponse,
            method="GET",
            path=f"/v1/instances/templates/{uuid}",
            query={
                "details": details,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_template_instances(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        details: bool | None = None,
        count: int | None = None,
        tags: list[str] | None = None,
        from_: str | None = None,
        order: models.PaginationOrder | None = None,
        sortby: models.PaginationSortBy | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetTemplateInstancesResponse:
        """List template instances"""
        return await self._request(
            models.GetTemplateInstancesResponse,
            method="GET",
            path="/v1/instances/templates",
            query={
                "uuid": uuid,
                "name": name,
                "details": details,
                "count": count,
                "tags": tags,
                "from": from_,
                "order": order,
                "sortby": sortby,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def start_instance_by_uuid(
        self,
        uuid: str,
        *,
        body: models.StartInstanceByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.StartInstancesResponse:
        """Start Instance by UUID"""
        return await self._request(
            models.StartInstancesResponse,
            method="PUT",
            path=f"/v1/instances/{uuid}/start",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def start_instances(
        self,
        *,
        body: list[models.StartInstancesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.StartInstancesResponse:
        """Start Instances"""
        return await self._request(
            models.StartInstancesResponse,
            method="PUT",
            path="/v1/instances/start",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def stop_instance_by_uuid(
        self,
        uuid: str,
        *,
        body: models.StopInstanceByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.StopInstancesResponse:
        """Stop Instance by UUID"""
        return await self._request(
            models.StopInstancesResponse,
            method="PUT",
            path=f"/v1/instances/{uuid}/stop",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def stop_instances(
        self,
        *,
        body: list[models.StopInstancesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.StopInstancesResponse:
        """Stop Instances"""
        return await self._request(
            models.StopInstancesResponse,
            method="PUT",
            path="/v1/instances/stop",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def suspend_instance_by_uuid(
        self,
        uuid: str,
        *,
        body: models.SuspendInstanceByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.SuspendInstancesResponse:
        """Suspend Instance by UUID"""
        return await self._request(
            models.SuspendInstancesResponse,
            method="PUT",
            path=f"/v1/instances/{uuid}/suspend",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def suspend_instances(
        self,
        *,
        body: list[models.SuspendInstancesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.SuspendInstancesResponse:
        """Suspend Instances"""
        return await self._request(
            models.SuspendInstancesResponse,
            method="PUT",
            path="/v1/instances/suspend",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_checkpoint_instance_by_uuid(
        self,
        uuid: str,
        *,
        body: models.UpdateCheckpointInstanceByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateCheckpointInstancesResponse:
        """Update checkpoint instance by UUID"""
        return await self._request(
            models.UpdateCheckpointInstancesResponse,
            method="PATCH",
            path=f"/v1/instances/checkpoints/{uuid}",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_checkpoint_instances(
        self,
        *,
        body: list[models.UpdateCheckpointInstancesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateCheckpointInstancesResponse:
        """Update checkpoint instances"""
        return await self._request(
            models.UpdateCheckpointInstancesResponse,
            method="PATCH",
            path="/v1/instances/checkpoints",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_instance_by_uuid(
        self,
        uuid: str,
        *,
        body: models.UpdateInstanceByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateInstancesResponse:
        """Update Instance by UUID"""
        return await self._request(
            models.UpdateInstancesResponse,
            method="PATCH",
            path=f"/v1/instances/{uuid}",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_instances(
        self,
        *,
        body: list[models.UpdateInstancesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateInstancesResponse:
        """Update Instances"""
        return await self._request(
            models.UpdateInstancesResponse,
            method="PATCH",
            path="/v1/instances",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_template_instance_by_uuid(
        self,
        uuid: str,
        *,
        body: models.UpdateTemplateInstanceByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateTemplateInstancesResponse:
        """Update template instance by UUID"""
        return await self._request(
            models.UpdateTemplateInstancesResponse,
            method="PATCH",
            path=f"/v1/instances/templates/{uuid}",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_template_instances(
        self,
        *,
        body: list[models.UpdateTemplateInstancesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateTemplateInstancesResponse:
        """Update template instances"""
        return await self._request(
            models.UpdateTemplateInstancesResponse,
            method="PATCH",
            path="/v1/instances/templates",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def wait_instance_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.WaitInstancesResponse:
        """Wait for Instance State by UUID"""
        return await self._request(
            models.WaitInstancesResponse,
            method="GET",
            path=f"/v1/instances/{uuid}/wait",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def wait_instances(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        state: list[models.InstanceState] | None = None,
        timeout_ms: list[int] | None = None,
        timeout_s: list[int] | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.WaitInstancesResponse:
        """Wait for Instances States"""
        return await self._request(
            models.WaitInstancesResponse,
            method="GET",
            path="/v1/instances/wait",
            query={
                "uuid": uuid,
                "name": name,
                "state": state,
                "timeout_ms": timeout_ms,
                "timeout_s": timeout_s,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
