# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class ServiceGroupsApi(ApiClient):
    """Low-level "plumbing" client for the `ServiceGroups` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def create_service_group(
        self,
        *,
        body: models.CreateServiceGroupRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.CreateServiceGroupResponse:
        """Create Service Group"""
        return await self._request(
            models.CreateServiceGroupResponse,
            method="POST",
            path="/v1/services",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_service_group_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteServiceGroupsResponse:
        """Delete Service Group by UUID"""
        return await self._request(
            models.DeleteServiceGroupsResponse,
            method="DELETE",
            path=f"/v1/services/{uuid}",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_service_groups(
        self,
        *,
        body: list[models.NameOrUUID],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteServiceGroupsResponse:
        """Delete Service Groups"""
        return await self._request(
            models.DeleteServiceGroupsResponse,
            method="DELETE",
            path="/v1/services",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_service_group_by_uuid(
        self,
        uuid: str,
        *,
        details: bool | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetServiceGroupsResponse:
        """Get Service Group by UUID"""
        return await self._request(
            models.GetServiceGroupsResponse,
            method="GET",
            path=f"/v1/services/{uuid}",
            query={
                "details": details,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_service_groups(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        details: bool | None = None,
        count: int | None = None,
        from_: str | None = None,
        order: models.PaginationOrder | None = None,
        sortby: models.PaginationSortBy | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetServiceGroupsResponse:
        """List Service Groups"""
        return await self._request(
            models.GetServiceGroupsResponse,
            method="GET",
            path="/v1/services",
            query={
                "uuid": uuid,
                "name": name,
                "details": details,
                "count": count,
                "from": from_,
                "order": order,
                "sortby": sortby,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_service_group_by_uuid(
        self,
        uuid: str,
        *,
        body: models.UpdateServiceGroupByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateServiceGroupsResponse:
        """Update Service Group by UUID"""
        return await self._request(
            models.UpdateServiceGroupsResponse,
            method="PATCH",
            path=f"/v1/services/{uuid}",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_service_groups(
        self,
        *,
        body: list[models.UpdateServiceGroupsRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateServiceGroupsResponse:
        """Update Service Groups"""
        return await self._request(
            models.UpdateServiceGroupsResponse,
            method="PATCH",
            path="/v1/services",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
