# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class UsersApi(ApiClient):
    """Low-level "plumbing" client for the `Users` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def add_users(
        self,
        *,
        body: models.AddUsersRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.AddUsersResponse:
        """Add Users"""
        return await self._request(
            models.AddUsersResponse,
            method="POST",
            path="/v1/users",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_user(
        self,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.QuotasResponse:
        """Get Current User Quotas"""
        return await self._request(
            models.QuotasResponse,
            method="GET",
            path="/v1/users/quotas",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_user_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.QuotasResponse:
        """Get User Quotas by UUID"""
        return await self._request(
            models.QuotasResponse,
            method="GET",
            path=f"/v1/users/{uuid}/quotas",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
