# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from urllib.parse import quote

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class UsersApi(ApiClient):
    """Low-level "plumbing" client for the `users` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def get_user(
        self,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.QuotasResponse:
        """Get Current User Quotas"""
        return await self.request(
            models.QuotasResponse,
            method="GET",
            path="/v1/users/quotas",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_user_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.QuotasResponse:
        """Get User Quotas by UUID"""
        return await self.request(
            models.QuotasResponse,
            method="GET",
            path=f"/v1/users/{quote(uuid, safe='')}/quotas",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
