# Code generated by openapi-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Any

from ...core.http import UNSET, ApiClient, TimeoutOption
from . import models_gen as models


class VolumesApi(ApiClient):
    """Low-level "plumbing" client for the `Volumes` resource.

    Methods mirror the OpenAPI specification and return the raw response
    envelope. The idiomatic clients are built on top of this.
    """

    async def attach_volume_by_uuid(
        self,
        uuid: str,
        *,
        body: models.AttachVolumeByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.AttachVolumesResponse:
        """Attach Volume by UUID"""
        return await self._request(
            models.AttachVolumesResponse,
            method="PUT",
            path=f"/v1/volumes/{uuid}/attach",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def attach_volumes(
        self,
        *,
        body: list[models.AttachVolumesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.AttachVolumesResponse:
        """Attach Volumes"""
        return await self._request(
            models.AttachVolumesResponse,
            method="PUT",
            path="/v1/volumes/attach",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def clone_volume_by_uuid(
        self,
        uuid: str,
        *,
        body: models.CloneVolumeByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.CloneVolumesResponse:
        """Clone Volume by UUID"""
        return await self._request(
            models.CloneVolumesResponse,
            method="POST",
            path=f"/v1/volumes/{uuid}/clone",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def clone_volumes(
        self,
        *,
        body: list[models.CloneVolumesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.CloneVolumesResponse:
        """Clone Volumes"""
        return await self._request(
            models.CloneVolumesResponse,
            method="POST",
            path="/v1/volumes/clone",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def create_template_volume(
        self,
        *,
        body: list[models.NameOrUUID],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.CreateTemplateVolumesResponse:
        """Create template volume"""
        return await self._request(
            models.CreateTemplateVolumesResponse,
            method="POST",
            path="/v1/volumes/templates",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def create_volume(
        self,
        *,
        body: models.CreateVolumeRequest,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.CreateVolumeResponse:
        """Create Volume"""
        return await self._request(
            models.CreateVolumeResponse,
            method="POST",
            path="/v1/volumes",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_template_volume_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteTemplateVolumesResponse:
        """Delete template volume by UUID"""
        return await self._request(
            models.DeleteTemplateVolumesResponse,
            method="DELETE",
            path=f"/v1/volumes/templates/{uuid}",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_template_volumes(
        self,
        *,
        body: list[models.NameOrUUID],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteTemplateVolumesResponse:
        """Delete template volumes"""
        return await self._request(
            models.DeleteTemplateVolumesResponse,
            method="DELETE",
            path="/v1/volumes/templates",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_volume_by_uuid(
        self,
        uuid: str,
        *,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteVolumesResponse:
        """Delete Volume by UUID"""
        return await self._request(
            models.DeleteVolumesResponse,
            method="DELETE",
            path=f"/v1/volumes/{uuid}",
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def delete_volumes(
        self,
        *,
        body: list[models.NameOrUUID],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DeleteVolumesResponse:
        """Delete Volumes"""
        return await self._request(
            models.DeleteVolumesResponse,
            method="DELETE",
            path="/v1/volumes",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def detach_volume_by_uuid(
        self,
        uuid: str,
        *,
        body: models.DetachVolumeByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DetachVolumesResponse:
        """Detach Volume by UUID"""
        return await self._request(
            models.DetachVolumesResponse,
            method="PUT",
            path=f"/v1/volumes/{uuid}/detach",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def detach_volumes(
        self,
        *,
        body: list[models.DetachVolumesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.DetachVolumesResponse:
        """Detach Volumes"""
        return await self._request(
            models.DetachVolumesResponse,
            method="PUT",
            path="/v1/volumes/detach",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_template_volume_by_uuid(
        self,
        uuid: str,
        *,
        details: bool | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetTemplateVolumesResponse:
        """Get template volume by UUID"""
        return await self._request(
            models.GetTemplateVolumesResponse,
            method="GET",
            path=f"/v1/volumes/templates/{uuid}",
            query={
                "details": details,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_template_volumes(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        details: bool | None = None,
        count: int | None = None,
        from_: str | None = None,
        tags: list[str] | None = None,
        order: models.PaginationOrder | None = None,
        sortby: models.PaginationSortBy | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetTemplateVolumesResponse:
        """List template volumes"""
        return await self._request(
            models.GetTemplateVolumesResponse,
            method="GET",
            path="/v1/volumes/templates",
            query={
                "uuid": uuid,
                "name": name,
                "details": details,
                "count": count,
                "from": from_,
                "tags": tags,
                "order": order,
                "sortby": sortby,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_volume_by_uuid(
        self,
        uuid: str,
        *,
        details: bool | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetVolumesResponse:
        """Get Volume by UUID"""
        return await self._request(
            models.GetVolumesResponse,
            method="GET",
            path=f"/v1/volumes/{uuid}",
            query={
                "details": details,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def get_volumes(
        self,
        *,
        uuid: list[str] | None = None,
        name: list[str] | None = None,
        details: bool | None = None,
        count: int | None = None,
        from_: str | None = None,
        tags: list[str] | None = None,
        order: models.PaginationOrder | None = None,
        sortby: models.PaginationSortBy | None = None,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.GetVolumesResponse:
        """List Volumes"""
        return await self._request(
            models.GetVolumesResponse,
            method="GET",
            path="/v1/volumes",
            query={
                "uuid": uuid,
                "name": name,
                "details": details,
                "count": count,
                "from": from_,
                "tags": tags,
                "order": order,
                "sortby": sortby,
            },
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_template_volume_by_uuid(
        self,
        uuid: str,
        *,
        body: models.UpdateTemplateVolumeByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateTemplateVolumesResponse:
        """Update template volume by UUID"""
        return await self._request(
            models.UpdateTemplateVolumesResponse,
            method="PATCH",
            path=f"/v1/volumes/templates/{uuid}",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_template_volumes(
        self,
        *,
        body: list[models.UpdateTemplateVolumesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateTemplateVolumesResponse:
        """Update template volumes"""
        return await self._request(
            models.UpdateTemplateVolumesResponse,
            method="PATCH",
            path="/v1/volumes/templates",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_volume_by_uuid(
        self,
        uuid: str,
        *,
        body: models.UpdateVolumeByUUIDRequestBody,
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateVolumesResponse:
        """Update Volume by UUID"""
        return await self._request(
            models.UpdateVolumesResponse,
            method="PATCH",
            path=f"/v1/volumes/{uuid}",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )

    async def update_volumes(
        self,
        *,
        body: list[models.UpdateVolumesRequestItem],
        headers: Mapping[str, str] | None = None,
        base_url: str | None = None,
        timeout: TimeoutOption = UNSET,
    ) -> models.UpdateVolumesResponse:
        """Update Volumes"""
        return await self._request(
            models.UpdateVolumesResponse,
            method="PATCH",
            path="/v1/volumes",
            body=body,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
        )
