name: sync

on:
  workflow_dispatch:
    inputs:
      channel:
        default: prod-stable
        description: |
          The name of the release channel.
          One of: [prod-stable, prod-staging]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.channel }}

    - name: Generate
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
      run: |
        make generate
        make fmt

    - name: Show diff
      shell: bash
      run: |
        git diff

    - name: Generate branch ID
      id: id
      run: |
        BRANCH="sync/$(date +'%Y%m%d%H%M%S')"
        echo "name=${BRANCH}" >>"${GITHUB_OUTPUT}"

    - name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GH_PAT }}
        base: ${{ inputs.channel }}
        commit-message: "sync: Update Python SDK from OpenAPI spec"
        title: "sync: Update Python SDK from OpenAPI spec"
        branch: ${{ steps.id.outputs.name }}
        committer: Unikraft Bot <monkey@unikraft.io>
        author: Unikraft Bot <monkey@unikraft.io>
        add-paths: controlplane,platform
        signoff: true
